name: CI

on: [push]

jobs:
  build:
    name: Build & Upload to dockerhub
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Use go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout source
      uses: actions/checkout@v1
    # - name: Run tests
    #   run: go test ./...
    - name: Build image
      run: docker build . --file Dockerfile --tag piotrpersona/gg:${GITHUB_SHA}
    - name: Login to dockerhub.io
      uses: azure/docker-login@v1
      with:
        loginServer: 'index.docker.io'
        username: ${{ secrets.dockerHubUsername }}
        password: ${{ secrets.dockerHubToken }}
    - name: Push image
      run: docker push piotrpersona/gg:${GITHUB_SHA}
